USE [master]
GO
/****** Object:  Database [NLC_Orders]    Script Date: 12/10/2023 2:55:53 PM ******/
CREATE DATABASE [NLC_Orders]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NLC_Orders', FILENAME = N'/var/opt/mssql/data/NLC_Orders.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NLC_Orders_log', FILENAME = N'/var/opt/mssql/data/NLC_Orders_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [NLC_Orders] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NLC_Orders].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NLC_Orders] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NLC_Orders] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NLC_Orders] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NLC_Orders] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NLC_Orders] SET ARITHABORT OFF 
GO
ALTER DATABASE [NLC_Orders] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NLC_Orders] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NLC_Orders] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NLC_Orders] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NLC_Orders] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NLC_Orders] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NLC_Orders] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NLC_Orders] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NLC_Orders] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NLC_Orders] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NLC_Orders] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NLC_Orders] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NLC_Orders] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NLC_Orders] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NLC_Orders] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NLC_Orders] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NLC_Orders] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NLC_Orders] SET RECOVERY FULL 
GO
ALTER DATABASE [NLC_Orders] SET  MULTI_USER 
GO
ALTER DATABASE [NLC_Orders] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NLC_Orders] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NLC_Orders] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NLC_Orders] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NLC_Orders] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NLC_Orders] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [NLC_Orders] SET QUERY_STORE = ON
GO
ALTER DATABASE [NLC_Orders] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [NLC_Orders]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 12/10/2023 2:55:53 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [uniqueidentifier] NOT NULL,
	[UserId] [int] NOT NULL,
	[Region] [nvarchar](10) NULL,
	[ShowId] [uniqueidentifier] NOT NULL,
	[Time] [datetimeoffset](7) NOT NULL,
	[Status] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Orders] ADD  CONSTRAINT [DF_Orders_Time]  DEFAULT (sysdatetimeoffset()) FOR [Time]
GO
ALTER TABLE [dbo].[Orders] ADD  CONSTRAINT [DF_Orders_Status]  DEFAULT ((0)) FOR [Status]
GO
USE [master]
GO
ALTER DATABASE [NLC_Orders] SET  READ_WRITE 
GO
