USE [master]
GO
/****** Object:  Database [NLC_Cinemas_Fi]    Script Date: 12/16/2023 4:10:40 PM ******/
CREATE DATABASE [NLC_Cinemas_Fi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NLC_Cinemas_Fi', FILENAME = N'/var/opt/mssql/data/NLC_Cinemas_Fi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NLC_Cinemas_Fi_log', FILENAME = N'/var/opt/mssql/data/NLC_Cinemas_Fi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NLC_Cinemas_Fi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ARITHABORT OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET RECOVERY FULL 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET  MULTI_USER 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET QUERY_STORE = ON
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [NLC_Cinemas_Fi]
GO
/****** Object:  Table [dbo].[Cinemas]    Script Date: 12/16/2023 4:10:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cinemas](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Cinemas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Shows]    Script Date: 12/16/2023 4:10:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Shows](
	[Id] [uniqueidentifier] NOT NULL,
	[CinemaId] [uniqueidentifier] NOT NULL,
	[MovieId] [uniqueidentifier] NOT NULL,
	[StartTime] [datetimeoffset](7) NOT NULL,
	[Duration] [int] NOT NULL,
 CONSTRAINT [PK_Shows] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Shows] ADD  CONSTRAINT [DF_Shows_StartTime]  DEFAULT (getdate()) FOR [StartTime]
GO
ALTER TABLE [dbo].[Shows] ADD  CONSTRAINT [DF_Shows_Duration]  DEFAULT ((100)) FOR [Duration]
GO
USE [master]
GO
ALTER DATABASE [NLC_Cinemas_Fi] SET  READ_WRITE 
GO
